### ISSUE TITLE
Order matters for checking equality of structure

### ISSUE THREAD

**Issue by bpuchala** [materialsproject/pymatgen#3504] opened 2023-12-06 17:31 UTC
It can matter what is on the left hand side or right hand side of `Structure.__eq__`. For example, the following asserts pass:

```py
from pymatgen.core import IStructure


lattice_vectors = [[5.692, 0.0, 0.0], [0.0, 5.692, 0.0], [0.0, 0.0, 5.692]]
coords_frac = [
    [0.0, 0.0, 0.0],
    [0.0, 0.5, 0.5],
    [0.5, 0.0, 0.5],
    [0.5, 0.5, 0.0],
    [0.5, 0.5, 0.5],
    [0.5, 0.0, 0.0],
    [0.0, 0.5, 0.0],
    [0.0, 0.0, 0.5],
]
element_structure = IStructure(
    lattice=lattice_vectors,
    species=["Na"] * 4 + ["Cl"] * 4,
    coords=coords_frac,
    coords_are_cartesian=False,
)
species_structure = IStructure(
    lattice=lattice_vectors,
    species=["Na+"] * 4 + ["Cl-"] * 4,
    coords=coords_frac,
    coords_are_cartesian=False,
)
assert element_structure != species_structure
assert species_structure == element_structure
```

This seems to come down to the implementations of `Species.__eq__` vs `ElementBase.__eq__` and how inheritance is handled. `ElementBase.__eq__` uses ``isinstance(other, Element)``, which allows the lhs to be an `Element` and the rhs to be a `Species` with any oxidation state and still return True. I expected that `==` would either in effect convert the Element to a Species with oxidation state 0 before comparison or always return False if the types were not the same, but I'm not sure what the developers intend.

**Comment by janosh** [comment] 2023-12-07 14:57
Oh dear, loss of symmetry in `__eq__` is pretty serious, esp. in the core `Structure` class.
@bpuchala Thanks for reporting and thanks for finding the root cause! 🙏 

I'm in favor of making `Structure.__eq__` more discriminative by promoting `Elements` to `Species` with oxi state 0 so that

```py
element_structure == species_structure
>>> False
# and
species_structure == element_structure
>>> False
```

 but I'm interested to hear @shyuep and @mkhorton's opinions.

@bpuchala Would you be able to submit a fix for this that implements the type promotion so we can see if there are any unintended downstream implications?

**Comment by bpuchala** [comment] 2023-12-07 17:08
> @bpuchala Would you be able to submit a fix for this that implements the type promotion so we can see if there are any unintended downstream implications?

Sorry, I'm just a user here :)

**Comment by shyuep** [comment] 2023-12-08 18:37
I would just fix Element such that it only equates equal to Element and not Specie. I dislike the ElementBase implementation.  I think it overcomplicates matters relative to just a straight Enum.

**Comment by janosh** [comment] 2023-12-08 18:44
> I would just fix Element such that it only equates equal to Element and not Specie.

That's already the case.

```py
from pymatgen.core import Element, Species

Element('O') == Species('O')
>>> False
```
> I dislike the `ElementBase` implementation. I think it overcomplicates matters relative to just a straight Enum.

I've said the same thing in the past. IIRC @mkhorton had some reservations about that.

**Closed** 2023-12-08 18:46 UTC
Labels: bug, core, urgent
