### ISSUE TITLE
SpacegroupAnalyzer.get_conventional_standard_structure returns a wrong structure

### ISSUE THREAD

**Issue by lan496** [materialsproject/pymatgen#1929] opened 2020-08-14 12:31 UTC
**To Reproduce**
If I understand correctly, a structure and a symmetry-refined one have the same minimum distance between sites.
So, three structures `structure`, `conventional_refined`, and `spglib_refined` in the following script should have the same minimum distance.

```python
import numpy as np
from pymatgen.core import Structure
from pymatgen.analysis.structure_analyzer import SpacegroupAnalyzer


def min_dist(structure):
    all_dists = structure.distance_matrix[np.triu_indices(structure.num_sites, 1)]
    return np.min(all_dists)


if __name__ == '__main__':
    # spacegroup: C2/m
    matrix = [[3.945, 0.0, 3.945], [0.0, 3.945, 3.945], [0.0, 0.0, 11.834999999999999]]
    species = ['O'] * 7
    frac_coords = np.array([
        [0., 0.5, 0.66666667],
        [0.5, 0., 0.],
        [0.5, 0., 0.33333333],
        [0.5, 0., 0.66666667],
        [0.5, 0.5, -0.33333333],
        [0.5, 0.5, 0.],
        [0.5, 0.5, 0.33333333],
    ])
    structure = Structure(matrix, species, frac_coords)
    print("original:", min_dist(structure))

    sga = SpacegroupAnalyzer(structure)

    conventional_refined = sga.get_conventional_standard_structure()
    print("conventional_standard:", min_dist(conventional_refined))

    spglib_refined = sga.get_refined_structure()
    print("refine_cell:", min_dist(spglib_refined))

    conventional_refined.to(fmt='cif', filename='conventional_standard.cif', symprec=1e-2)
    spglib_refined.to(fmt='cif', filename='refined.cif', symprec=1e-2)
```

But I got the following output. The structure created by `SpacegroupAnalyzer.get_conventional_standard_structure` has a different distance from that of the original structure.
```
original: 2.789536223885567
conventional_standard: 1.610539489774544
refine_cell: 2.7895361959902023
```

**Screenshots**
The structure created by `SpacegroupAnalyzer.get_conventional_standard_structure` is as follows:
![conventional](https://user-images.githubusercontent.com/7272505/90248981-a55b0600-de74-11ea-9275-23a08e396cb1.png)

The structure created by `SpacegroupAnalyzer.get_refined_structure` is as follows:
![refined](https://user-images.githubusercontent.com/7272505/90249001-ab50e700-de74-11ea-816c-2704b18e8849.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu16.04
 - Version: 2020.8.13

**Comment by mkhorton** [comment] 2020-08-14 18:55
Agreed this looks like a serious bug. I'm looking at these lines in particular:

https://github.com/materialsproject/pymatgen/blob/v2020.8.13/pymatgen/symmetry/analyzer.py#L547-L597

I didn't write this code so it'll take me a while to understand what's meant to be happening here.

**Comment by mkhorton** [comment] 2020-08-14 19:00
Interestingly, I'm not sure I can reproduce this on pymatgen 2020.7.14, still investigating ...

**Comment by shyuep** [comment] 2020-08-14 19:02
@mkhorton Check if any of the cleanup that I did caused this. But if it did, seriously the person who wrote the code in the first place should have implemented unittests.

**Comment by mkhorton** [comment] 2020-08-14 20:36
@shyuep I don't think it was those changes, I was able to reproduce on 2020.7.14. Agreed on unit tests, we can use this one + generate some more. Structures don't even `match` in this case! I can imagine a fairly extensive unit test for a set of structures + checking they match before and after getting them in their conventional setting.

@Ian496, haven't got a fix yet, but thank you for such a nice reproducible example ... helps a lot

**Comment by mkhorton** [comment] 2020-08-14 20:54
It seems odd that in the `conventional_refined = sga.get_conventional_standard_structure()` all the z co-ordinates have been zeroed out. The transform matrix `transf` is:

```
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
```

So regardless of what the original z fractional co-ordinate is, it would always become zero.

This gets set to `1` explicitly here:

https://github.com/materialsproject/pymatgen/blob/185cb592cc0710e6882b3f57177112e3d86414d2/pymatgen/symmetry/analyzer.py#L549

but then gets set back to `0` here:

https://github.com/materialsproject/pymatgen/blob/185cb592cc0710e6882b3f57177112e3d86414d2/pymatgen/symmetry/analyzer.py#L595

**Comment by mkhorton** [comment] 2020-08-14 20:56
Resetting it back to `transf[2] = [0, 0, 1]` gives the correct result and fixes the issue here, but without code comments or a clear understanding of what the original code is doing, I can't say if this is an appropriate fix.

**Comment by lan496** [comment] 2020-08-15 08:00
It seems the bug in `get_conventional_standard_structure` for monoclinic also relates to https://github.com/materialsproject/pymatgen/issues/1543. 
`SpacegroupAnalyzer` with default symprec judges a structure in this issue as C2/m.

**Comment by mkhorton** [comment] 2020-08-21 02:23
Just adding a note here for test coverage: https://coveralls.io/builds/27639791/source?filename=pymatgen%2Fsymmetry%2Fanalyzer.py#L465

There are a few important branches not covered by existing tests.

**Comment by mkhorton** [comment] 2020-08-21 03:20
I committed the fix here: https://github.com/materialsproject/pymatgen/commit/f9226b79b8f9ccd0b305e557c9e4878e096bfc77 but I'm not satisfied this issue is closed until we can add some additional tests to make sure the entire function is covered.

**Closed** 2023-08-13 16:33 UTC
