### ISSUE TITLE
About a min-pymatgen version including core classes

### ISSUE THREAD

**Issue by gVallverdu** [materialsproject/pymatgen#1744] opened 2020-01-27 08:55 UTC
Hi !

I wonder if it could be possible in any way to distribute a kind of small/min/light version of pymatgen including only core classes ? Now pymatgen is a quite large python packages (git repo is about 1.5 Go). All different modules are really interesting but sometimes, if you want to develop a new application, what you need essentially are the `Molecule` and `Structure` classes.  These classes are really convenient, easy to use and as you said "fairly robust" ;). Thus setting pymatgen as requirements will increase a log the size of needed library only for core classes.

Another goal could be the use of pymatgen for server applications. Thus a light version of the package may be appreciable.

Thus, the idea/proposition is to talk about the possibility to extract mainly the contains of the core module and the `Molecule` and `Structure` classes in a min/light pymatgen version ? On the contrary if there is a current way or python strategy in order to do that, I am really interesting. Maybe I am completely wrong and I should write pymatgen as requirements without considering the size.

**Comment by gVallverdu** [comment] 2020-01-28 13:19
Hi,
I understand and agree that splitting pymatgen will certainly lead to more stuff ... 

> So we would definitely still encourage use of pymatgen for its core classes alone.

I will do that ! As you said I just don't have to hesitate putting pymatgen as requierments !

Thanks for the comment

**Comment by shyuep** [comment] 2020-01-28 15:40
Thanks. As @mkhorton said, we considered this carefully. The size of pymatgen is mainly an issue for people who need to clone the entire repo, which has gotten quite sizable due to the test files. While we can prune the test files a little and start the repo from scratch, it is not going to make a meaningfully large difference.

The problem is that I know of no good way to implement a plugin system for Python packages. Ideally, I would want to be able to release pymatgen.core (and perhaps a few other critical functionality like entries and electronic structure) as one package, and have pymatgen.analysis.anything as plugins. But the only way I know this works is for other packages to have different package names, e.g., pymatgen_diffusion is an example. I would very much rather it be pymatgen.diffusion to be consistent with everything pymatgen.

If anyone knows a good solution, we can revisit this.

**Comment by shyuep** [comment] 2020-01-28 16:03
I thought about it a bit more. I am going to implement something now that might help

**Comment by mkhorton** [comment] 2020-01-28 17:45
There is a plugin architecture available for Python in the standard library, https://packaging.python.org/guides/creating-and-discovering-plugins/ so we do have options.

There's also setup.py "extras" https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras so you can e.g. `pip install pymatgen[core]` with a separate set of dependencies, that's also an option.

To do this robustly we should look at the dependency graph between the various pymatgen subpackages/submodules, I think extracting core (perhaps with electronic_structure) should be fairly clean but I'm not sure about some of the others.

**Comment by shyuep** [comment] 2020-01-28 19:39
@mkhorton By all means you can try. I tried getting the plugin to work but it is difficult.

**Comment by mkhorton** [comment] 2020-01-28 19:50
Yeah, likewise, which is why I've left it on the back burner for now.

**Comment by shyuep** [comment] 2020-01-28 23:18
I figured out how to get this to work in some way. Pushed a minimal implementation. More details to follow.

**Comment by shyamd** [comment] 2020-04-13 03:05
An alternative here is namespace packages. @tschaume has been building MPContribs with this and we're switching emmet to those. See [PEP420](https://www.python.org/dev/peps/pep-0420/)

**Comment by janosh** [comment] 2023-06-05 18:13
Several namespace packages exist at this point:

- https://github.com/materialsproject/pymatgen-analysis-alloys
- https://github.com/materialsvirtuallab/pymatgen-analysis-diffusion
- https://github.com/materialsproject/pymatgen-analysis-defects
- https://github.com/JuDFTteam/pymatgen-io-fleur

which are also listed are here:

https://pymatgen.org/addons

`pymatgen.core` is still not installable, but I think we'd like to keep it that way. Closing this as not planned.

**Closed by janosh** 2023-06-05 18:13 UTC
