### ISSUE TITLE
get_primitive_standard_structure returns structure that doesn't match the original sturcutre

### ISSUE THREAD

**Issue by chenweis** [materialsproject/pymatgen#168] opened 2014-11-07 03:45 UTC
We recently found some static runs give very different energy_per_atom results from the original relaxation results. It seems the get_primitive_standard_structure used for the static runs gives a different structure from the input structure. 

Here's one example:

mpr=MPRester()
struct=mpr.get_structure_by_material_id("mp-684713", True)
standard_primitive_struct=SpacegroupAnalyzer(struct,
                                             symprec=0.1).get_primitive_standard_structure(False)
print StructureMatcher(primitive_cell=True, attempt_supercell=True, allow_subset=True).fit(struct, standard_primitive_struct)
for s in [struct, standard_primitive_struct]:
    print sorted([VoronoiCoordFinder(s).get_coordination_number(i) for i in range(len(s))], reverse=True)[:5]

The output is:
False
[5.468264142764663, 5.3980422434779465, 5.378317469545274, 5.3781566512430174, 5.197298392607815]
[6.094305973098741, 5.6656446821230135, 5.66564468210721, 5.469559081595328, 5.428248126158461]

So the StructureMatcher thinks the standard primitive structure doesn't match the original structure. And the coordination numbers given by the VoronoiCoordFinder are also very different between the two structures.

**Comment by shyuep** [comment] 2015-03-20 00:43
@hautierg Can you give an update on this? This bug is outstanding and severely affects the MP workflows. So this is rather critical to fix.

**Comment by terencezl** [comment] 2015-08-19 05:23
What could be the range of affected cases of this symmetry related issue? Apart from eye-spotting, it's difficult to figure out what's different before and after a structure transformation. So trusting the algorithm is particularly crucial...

**Comment by hautierg** [comment] 2015-08-19 09:04
This went out of my radar screen. Sorry about that. I looked back at it.
I believe the issue comes from  get_reduced_structure("LLL") that is called by get_primitive_standard_structure.

If I do:

    mpr=MPRester()
    struct=mpr.get_structure_by_material_id("mp-684713", True)
    struct_refined=struct.get_reduced_structure("LLL")
    print SpacegroupAnalyzer(struct).get_spacegroup()
    print StructureMatcher(primitive_cell=True, attempt_supercell=True, allow_subset=True).fit(struct, struct_refined)

I am getting:

P1 (1) spacegroup
False

@shyuep , who coded the "LLL" reduction in get_reduced_structure.

Note: this bug will only affect triclinic cells.

**Comment by shyuep** [comment] 2015-08-19 14:38
I just pushed a fix. The problem is not with any of the algos itself. It is with the fact that the LLL did not defensively copy the structure lattice, leading to modifications of the mutable np.array. That result in an error in structure matching.

**Closed by shyuep** 2015-08-19 14:38 UTC
Labels: Bugs
