### ISSUE TITLE
Missing some radii & mistakes in commonness of some oxidation states

### ISSUE THREAD

**Issue by volodiag** [materialsproject/pymatgen#1404] opened 2019-03-01 15:54 UTC
There are some mistakes in the common oxidation state of some elements and some radii are missing.

When I do the following :

from pymatgen.core.periodic_table import Element
for Elem in Element:
    print(Elem)
    print(Element(Elem).common_oxidation_states)
    print(Element(Elem).ionic_radii)

I have the following 
Ni
(2,)
{3: 0.74}
--> but in Shannon table oxidation state 3 is reported as well (--> common) and crystal radius of Ni2+ is 0.84 Å.

Sn
(-4, 2, 4)
{4: 0.83}
--> but in Shannon table crystal radius of Sn2+ is 1.36 Å.

Te
(-2, 2, 4, 6)
{-2: 2.07, 4: 1.11, 6: 0.7}
--> but in Shannon table Te2+ is not present (--> uncommon) 

I am using pymatgen version from 2018.08.30 on python 3.6.6. with ubuntu 18.04.2 LTS

Kind regard

**Comment by shyuep** [comment] 2019-03-02 16:27
Thanks. I agree the ionic radii tabulation is incomplete. In the first place, only one ionic radius is assigned to each oxidation state. Some of the elements have multiple ionic radius depending on coordination environment, oxidation state as well as high/low spin. The source of the ionic radii is https://www.wikiwand.com/en/Ionic_radius . I believe the reason why some of these are missing is because they are not in the oct environment. For Ni, the problem is that there are high and low spins, which affect the ionic radii. We can try to correct it.

**Comment by shyuep** [comment] 2019-03-03 02:17
Actually I just realized that get_shannon_radius would already do what you want. Pls see that method for Elements.

**Closed by shyuep** 2019-03-03 02:17 UTC
