### ISSUE TITLE
Possible issue with DLSVolumePredictor

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/pymatgen#1295] opened 2018-10-03 06:13 UTC
**Describe the bug**

In a very small number of cases, `DLSVolumePredictor` seems to be giving non-sensical volumes.

**To Reproduce**

This structure almost made it to MP (though way off the hull!):

```
{'@module': 'pymatgen.core.structure',
 '@class': 'Structure',
 'charge': None,
 'lattice': {'matrix': [[17.05509494, 0.0, 0.0],
   [0.0, 21.75339345, -0.74777563],
   [0.0, -0.74777563, 21.75339345]]},
 'sites': [{'species': [{'element': 'V', 'occu': 1}],
   'abc': [-0.0, -0.0, -0.0],
   'properties': {'magmom': 3.454}},
  {'species': [{'element': 'Sb', 'occu': 1}],
   'abc': [0.5, 0.5, 0.5],
   'properties': {'magmom': 0.106}},
  {'species': [{'element': 'O', 'occu': 1}],
   'abc': [-0.0, 0.36862268, 0.36862268],
   'properties': {'magmom': 1.402}},
  {'species': [{'element': 'O', 'occu': 1}],
   'abc': [0.5, 0.55918021, 0.44081979],
   'properties': {'magmom': 0.327}},
  {'species': [{'element': 'O', 'occu': 1}],
   'abc': [0.5, 0.44081979, 0.55918021],
   'properties': {'magmom': 0.327}},
  {'species': [{'element': 'O', 'occu': 1}],
   'abc': [-0.0, 0.63137732, 0.63137732],
   'properties': {'magmom': 1.402}}]}
```

I haven't got the exact input structure to hand, but the input was sensible, but the DLS predicted volume is 8786.83 Å^3, or 9226.18 Å^3 with icsd_vol=True.

**Expected behavior**

Perhaps some sanity checks? e.g. a plausible density range or % vol change? We're currently running DLSVolumePredictor against MP inputs by default, but in many cases the input volumes are not far off and may only need to change by a few %. Very large changes seem like they'd be relatively rare.

**Comment by mkhorton** [comment] 2018-10-03 06:19
Also tagging @tschaume here

**Comment by mkhorton** [comment] 2018-10-03 16:20
Increasing cutoff by 10-20x (tried up to 80.0) also doesn't seem to change the result.

**Comment by shyuep** [comment] 2018-10-03 21:18
@computron Incidentally, why are we using DLS? In most instances, the RLS should work fine. As far as I know, we don't have any method of structure prediction from completely unknown crystals.

**Comment by computron** [comment] 2018-10-03 23:16
1. I don't know where DLS is being used by MP (or why it was chosen instead of RLS)
2. Sanity checks would be good
3. Crazy failures do happen with DLS, we've seen it before. DLS tries to make sure that no two atoms are "too close". If _any_ two atoms happen to be closer than DLS expects, the entire volume of the cell is expanded to bring the atoms to an "expected" distance. Two enhancements to mitigate this behavior would be to (i) look more at the "average" distance between sites rather than only the worst case scenario and (ii) allow for adjustments to the cell that are not wholesale full volume expansions.

For example, let's say you have a layered compound, and two atoms within a layer are "too close". We'll expand the entire cell, including the inter-layer vacuum distance, to bring those atoms further apart. Ideally in this situation, however, we could just shift along axes parallel to the layers and keep the inter-layer distance the same.

There are definitely problems with DLS, but the problem is we had an undergrad working one summer on it and I really didn't have much capacity to fix the issues myself. Most fixes ended up resembling some kind of energy model. Honestly, I think with some ML we could do much better than the published DLS model while retaining the "no reference structure" criterion which I think is nice to have.

Note that some limitations, like the one about only having the volume to expand on and not individual cell parameters, is also true for RLS. But I suspect RLS will have much fewer crazy failures.

**Comment by shyuep** [comment] 2018-10-03 23:29
For MP, I would suggest we use RLS *unless* there is no parent structure. Since RLS always starts from a known parent, it is very unlikely you have problems such as atoms being too close together.

I am by no means suggesting we fix the DLS algo - I think we have more important things we are all going after.

**Comment by computron** [comment] 2019-02-12 18:25
Given that DLS can give very bad results (even if sporadic, this method is often used in high-throughput), should we add a deprecation or warning to this technique? We might also add a warning if the final volume differs significantly from the initial volume.

It'd be nice if the code was still around somewhere, since it's referred to in a paper and anyone who is using it semi-carefully (e.g., with a check on the volume expansion) might still use it.

**Comment by computron** [comment] 2019-02-12 18:26
I would also suggest trying some of the crazy failures with DLS using RLS to see if this problem is isolated to DLS or also happens with RLS. Both of them do have the problem that they scale volume in all directions, but it's possible / likely that the RLS error will be more controlled.

**Comment by shyuep** [comment] 2019-02-12 19:17
I would suggest just a warning. Technically, it is not a deprecation given that we are not substituting it for a newer method. It is just a different method for a different use case.

**Comment by computron** [comment] 2019-02-12 20:53
I recommend closing this based on PR #1392 as I don't think we'll fix it any further than this anytime soon

**Closed** 2019-02-12 21:01 UTC
