### ISSUE TITLE
Issue with WulffShape.show(): 3D image not rendering

### ISSUE THREAD

**Issue by jamesgil54** [materialsproject/pymatgen#2946] opened 2023-04-19 22:53 UTC
Hello! 

I've been struggling with the WulffShape.show() function. I am using the exact code from the tutorial scripts from https://matgenb.materialsvirtuallab.org/2017/04/03/Slab-generation-and-Wulff-shape.html. While the script outputs information about the Wulff Construction such as the weighted surface energy and anisotropy, when calling WulffShape.show(), no 3D image is rendered in the popped-up figure. I have run this script on my computer and the computers of 2 of my colleagues. I wonder if this may be a problem with upgraded versions of Pymatgen and/or its compatibility with the latest versions of Python?

**Comment by janosh** [comment] 2023-04-19 23:13
Duplicate of #2900. As a temporary workaround, try the `get_plotly()` method instead.

**Closed by janosh** 2023-04-19 23:13 UTC

**Comment by jamesgil54** [comment] 2023-04-20 12:37
I see - using get_plotly worked! Thank you!
