### ISSUE TITLE
Crash in GaussianInput when using to_string(cart_coords=True)

### ISSUE THREAD

**Issue by vliegeois** [materialsproject/pymatgen#2865] opened 2023-02-28 11:47 UTC
**Describe the bug**

When creating a GaussianInput object and calling `to_string(cart_coords=True)` method, it raises an error:
  File "python3.10/site-packages/pymatgen/io/gaussian.py", line 423, in get_cart_coords
    outs.append(" ".join(site.species_string, " ".join([to_s(j) for j in site.coords])))
TypeError: str.join() takes exactly one argument (2 given)

This bug was created in commit 0d2062a01bf0ccb36cb736c9a5d139787c55e4c1 on 6 January 2023:
Prefer generator over list comprehension where equivalent (#2793)

**To Reproduce**

Execute the following code with pymatgen 2023.1.9 and later

```
from pymatgen.core import Molecule
from pymatgen.io import gaussian
molfile = """
5
methane
C        0.0000000000        0.0000000000        0.0000000000
H        0.6364381313       -0.0720602423       -0.9058204889
H        0.6364393234       -0.0721551627        0.9058120847
H       -0.5344626307        0.9721659422        0.0000000000
H       -0.7384146452       -0.8279502988        0.0000000000
"""

mol = Molecule.from_str(molfile, fmt="xyz")
file = gaussian.GaussianInput(mol)

print(file.to_string(cart_coords=True))
```

**Fix**

The lines 421-423 in file pymatgen/io/gaussian.py now look like:
```
        outs = []
        for site in self._mol:
            outs.append(" ".join(site.species_string, " ".join([to_s(j) for j in site.coords])))
```

This does not works since the first join function call has two arguments: 
1) `site.species_string`
2) `" ".join([to_s(j) for j in site.coords])`

The code before the commit 0d2062a01bf0ccb36cb736c9a5d139787c55e4c1 contains `[]` for list comprehension like this:
```
        outs = []
        for site in self._mol:
            outs.append(" ".join([site.species_string, " ".join([to_s(j) for j in site.coords])]))
```
The square braquet in the second join function call can be removed to use generator expression but not in the first join.

Another possibility would be to remove the nested join functions with something like this:
```
        outs = []
        for site in self._mol:
            outs.append(" ".join([site.species_string] + [to_s(j) for j in site.coords]))
```

I do not think replacing list comprehension by generator expression is required for performance gain in this case

Regards

Vincent LIEGEOIS

**Comment by ConradJohnston** [comment] 2023-02-28 16:47
Duplicate of #2863 , by only a handful of hours.

**Comment by janosh** [comment] 2023-05-19 20:15
Thanks for linking these related issues. I wasn't aware of them when merging https://github.com/materialsproject/pymatgen/pull/2891. Closing this and #2863 now.

**Closed by janosh** 2023-05-19 20:15 UTC

**Comment by ConradJohnston** [comment] 2023-05-19 20:49
Thanks @janosh !
