### ISSUE TITLE
Bug in NearNeighbors.get_all_nn_info

### ISSUE THREAD

**Issue by utf** [materialsproject/pymatgen#1321] opened 2018-11-08 19:04 UTC
When the fractional coordinates of a site contain `1.`, the bonding to the site is duplicated.

**To Reproduce**

```python
from pymatgen.core.structure import Structure
from pymatgen.analysis.local_env import CrystalNN

cnn = CrystalNN()

sites =  [[0., 0.2, 0.2], [0, 0, 0]]

structure = Structure([7, 0, 0, 0, 7, 0, 0, 0, 7], ['I'] * len(sites), sites)

bonded_structure = cnn.get_bonded_structure(structure)
bonded_structure.get_connected_sites(0)
```

Returns 1 connected site, as expected. Changing the fractional coordinate of the site from `0.` to `1.`, should not affect the bonding as the site is in the same position. However:

```python
sites =  [[1., 0.2, 0.2], [0, 0, 0]]

structure = Structure([7, 0, 0, 0, 7, 0, 0, 0, 7], ['I'] * len(sites), sites)

bonded_structure = cnn.get_bonded_structure(structure)
bonded_structure.get_connected_sites(0)
```

Returns 2 connected sites. One with `jimage = (0, 0, 0)` and the other with `jimage = (1, 0, 0)`.

This seems to be due to the behavior of `_get_image` method in the `NearNeighbors` class, which does not consider wrapping of fractional coordinates:

```python
    @staticmethod
    def _get_image(frac_coords):
        """Private convenience method for get_nn_info,
        gives lattice image from provided PeriodicSite.

        Args:
            frac_coords ([float]*3): Fraction coordinates
        Returns:
            ((int)*3) Lattice image
        """
        # TODO: This is not numerically stable. Also, move to PeriodicSite? -WardLT, 23Jun18
        frac_coords = frac_coords
        return tuple(map(int, np.floor(frac_coords)))
```

This could also be related to #827

**Comment by mkhorton** [comment] 2018-11-08 21:08
Agree with @WardLT's comment here that this should probably just me moved to be a `image` property on PeriodicSite (as well as fixing the underlying bug).

**Comment by mkhorton** [comment] 2018-11-08 21:30
There also seems to be a larger issue with the construction of Structure and if fractional coords should be wrapped to [0,1) by default, which might help avoid some of these issues.

**Comment by WardLT** [comment] 2018-11-08 21:32
I agree with wrapping the fractional coordinates to [0, 1) by default and that providing fractional coordinates that do not match with the image is indeed a worry. Perhaps the solution is to only include the image id in the initializer or to wrap the fractional coordinates to [0, 1) (requiring that image is specified), and generate the fractional coordinates of an image on demand.

You are right that the image _should_ be determinable from the fractional coordinates. However, issues of numerical stability with testing whether a float exists in [0, 1) and the tendency of values near multiples of 1 to appear in practice (atoms often are placed on (0,0,0) in crystal structures) mean that, in practice, determining the image from fractional coordinates is dangerous.

**Comment by shyuep** [comment] 2018-11-08 21:34
No. Do not wrap the frac coordinates by default. there are good reasons to retain whatever coordinates there are, e.g., in MD simulations where a site in a different image is treated differently. By all means implement necessary processing in CrystalNN or NearestNeighbor. But please do not touch core classes like PeriodicSite or Structure unless there is a clear bug in those.

**Comment by mkhorton** [comment] 2018-11-08 22:02
Note we are not discussing having PeriodicSite wrap frae-coords, but whether frac-coords should be wrapped during Structure init, i.e. whether all sites in Structure should be in the origin image by default.

The modification to PeriodicSite suggested here is adding a `.image` property or method that would return what periodic image that site is in.

**Comment by WardLT** [comment] 2018-11-08 22:16
What do you think of having the ability to optionally provide a image to the initializer, and have the .image property return that image if provided and one determined by `floor` otherwise? We could make sure to test that the coordinates agree with the image id to avoid mismatches.

At present, the difficulty in avoiding numerically-unstable operations to determine a image id isn't a bug. and I agree with being hesitant to touch core classes. But, I think the "fractional coordinates -> image" is the root cause of the error @utf has pointed out. If so, it might be worth modifying the initializer of PeriodicSite by adding this optional argument, which would allow the ability to provide a numerically-stable `.image` property without breaking a huge amount of `pymatgen`.

I'll warn you: It's been a few months since I worked on the near neighbors classes, but my memory is that I had to abandon the `_get_image` operation due to the numerical issues with the `floor`. I wish I had documented tests that show it.

**Comment by mkhorton** [comment] 2018-11-08 22:38
>  [...] and one determined by floor otherwise? 

I think `floor` either works or it doesn't, if it's fundamentally buggy for this purpose we shouldn't use it at all. I am honestly surprised it's too unstable for this however, though this is not the first time this bug has cropped up.

> We could make sure to test that the coordinates agree with the image id to avoid mismatches.

How can you perform this test?  The whole point here is that we are saying that `[1, 0, 0]` might mean image `(0, 0, 0)` and not `(1, 0, 0)` ... if you could test whether co-ordinates agree with the image id to start with, we wouldn't need to have the additional arg you're proposing.

>  e.g., in MD simulations where a site in a different image is treated differently 

Keeping Structure as-is if there are good reasons for it (e.g. MD runs) makes sense, but I'm not convinced that sites shouldn't be wrapped by default. It seems sensible to define structures with sites in the origin image unless explicitly specified/requested otherwise. At the very least, I think it's sensible to do this within the NearNeighbor class.

**Comment by WardLT** [comment] 2018-11-08 22:44
> How can you perform this test?

Good point! I was initially thinking "given the wrapped fractional coordinates and the image, we can compute an expected fractional_coordinates." But then realized that wrapping to [0, 1) will also be problematic. It seems the best we could do is check if the image is within 1 cell of correct (assuming that we either have an erroneous round-up or round-down error). Hmm, more to think about.

**Comment by utf** [comment] 2018-11-08 22:46
The bug I described is different from the numerical precision error in `_get_image`. As you allude to above, the point at which `_get_image` is called is too late to do any sort of wrapping logic.

My bug can be fixed by redefining `get_all_nn_info` as follows:

```python
    def get_all_nn_info(self, structure):
        """Get a listing of all neighbors for all sites in a structure

        Args:
            structure (Structure): Input structure
        Return:
            List of NN site information for each site in the structure. Each
                entry has the same format as `get_nn_info`
        """
        structure.translate_sites(range(structure.num_sites), [1., 1., 1.],
                                  to_unit_cell=True)
        return [self.get_nn_info(structure, n) for n in range(len(structure))]
```

The `translate_sites` call will wrap the site before analysis. Are you guys happy if I make this change to tackle this issue for now?

**Comment by mkhorton** [comment] 2018-11-08 22:50
Also, it won't fix get_nn_info right? Only get_all_nn_info

**Comment by utf** [comment] 2018-11-08 22:51
Yeah good point, also won't fix `get_nn_images` etc.

**Comment by shyuep** [comment] 2018-11-08 23:20
@mkhorton In general we should avoid making modificaitons to inputs. If I construct a structure or periodic site and say the coordinates are [1.1, 0.5, 30.1], it is a safe bet that I do not want it converted to [0.1, 0.5, 0.1] by default. So default behavior should not map to origin cell. If this needs to be done for NearestNeighbor or other analysis, by all means. If the default behavior is changed, it will indeed wreck a lot of current code built on Structure.

**Comment by mkhorton** [comment] 2018-11-08 23:29
@shyuep Yes, I understand -- I'd usually go by 'principle of least surprise' + if user is explicitly requesting something, it makes sense to respect that. There are some cases where un-wrapped frac co-ords are being passed 'accidentally' however (sometimes I think as the result of a symmetry operation being applied, moving a site to 1.), and this does then cause unexpected behavior in some cases.

If this decision were being made today, my own preference would be a `wrap_coords=True` kwarg or similar in Structure, but given that this decision was already made a long time ago, I agree it's better to keep backwards compatibility.

**Comment by shyuep** [comment] 2018-11-08 23:47
@mkhorton Structure does have a `to_unit_cell` parameter?

**Comment by mkhorton** [comment] 2018-11-08 23:57
@shyuep Ah, indeed it does, my apologies! `to_unit_cell` is not in the docstring however :)

(`to_unit_cell` is mentioned in `.from_sites` but not in Structure/IStructure; likewise actually the `charge` kwarg is not in the docstring of Structure though it has been included in IStructure)

**Comment by lan496** [comment] 2019-02-22 12:30
How do you define an image of a given site in pymatgen?

I think there are two possible definitions:
(1) just warping fractional coordinates to [0, 1)
(current implementation in pymatgen.analysis.local_env.NearNeighbors)
```python
    @staticmethod
    def _get_image(frac_coords):
        """Private convenience method for get_nn_info,
        gives lattice image from provided PeriodicSite.

        Args:
            frac_coords ([float]*3): Fraction coordinates
        Returns:
            ((int)*3) Lattice image
        """
        # TODO: This is not numerically stable. Also, move to PeriodicSite? -WardLT, 23Jun18
        return tuple(map(int, np.floor(frac_coords)))
```

(2) displacement from original site(that do not have to be in unit cell), like this
```python
    @staticmethod
    def _get_image_new(structure, site):
        """Private convenience method for get_nn_info,
        gives lattice image from provided PeriodicSite and Structure.

        Returns:
            image: ((int)*3) Lattice image
        """
        original_site = structure[NearNeighbors._get_original_site(structure, site)]
        image = np.around(np.subtract(site.frac_coords, original_site.frac_coords))
        image = tuple(image.astype(int))
        return image
```

Both of definitions return the same result for atoms in unit cell(i.e. when fractional coordinates are contained in [0, 1)^3).
In the definition (1) we, however, have to handle numerical error and the bug in this issue.
On the other hand, we are free from handling numerical error in the definition (2) because displacement from fractional coords to corresponding original fractional coords are exactly integers.

If you think the definition (2) is good, I will create PR based on (2).

**Comment by mkhorton** [comment] 2019-02-22 17:10
I like definition (2), thank you for suggesting/offering to implement this.

**Closed** 2019-02-23 19:13 UTC
