### ISSUE TITLE
Unable to Determine CN # For Mixed Site Occupancies

### ISSUE THREAD

**Issue by GerardMattei** [materialsproject/pymatgen#1085] opened 2018-03-29 18:24 UTC
## System

* Pymatgen version: 2018.2.13
* Python version: 3
## Summary
Hello,
I am running into an error message when attempting to determine the CN # of mixed occupancies using the Voronoi NN class (sample code attached below). If I attempt to determine the CN # around an pymatgen periodic site with a single species, the .get_cn() method successfully returns a CN # of 12.

But if I then use the same structure, but replace the Pt site with Pt0.5Pd0.5, the method instead returns an error message. Since the structures for both are the same, this should also return a CN # of 12. A similar issue is encountered when using the .get_nn() method for mixed site occupancies.

If it helps, I just updated to the newest version of pymatgen (2/13/18). The VoronoiCoordFinder from Version 2017.8.21 was able to successfully return CN #'s, for either single or mixed occupancies.

Cheers and thank you for the help,
-Gerry

## Example code
from pymatgen.analysis.local_env import VoronoiNN
from pymatgen.ext.matproj import MPRester
from pymatgen.core.structure import Structure

with MPRester() as m:
    Pt = m.get_structure_by_material_id('mp-126')
    PtPd = m.get_structure_by_material_id('mp-126')
    PtPd['Pt'] = {'Pt': 0.5, 'Pd': 0.5}

print(Pt, PtPd)
print('Pt Coordination: ', VoronoiNN().get_cn(Pt, 0))
#This successfully returns a CN # of 12 around Pt[0].
print('PtPd Alloy Coordination: ', VoronoiNN().get_cn(PtPd, 0)) # This should also return a CN # of 12, but instead produces an attribute error.

**Comment by nisse3000** [comment] 2018-04-02 21:51
Hi @GerardMattei,

thanks for indicating this issue.  A couple of quick questions.

I'm trying to reproduce that the previous pymatgen version that you used would indeed give expected results. I tried one pymatgen version from August 20 (5e6f0f755a41016975c8e1137fd11c6810c39766) and one from August 21 (764da43fca24ba71978c331c9ecdf1e77a4cd13e).  With neither of these, I got it to work.  Have you used exactly this testing code in the past, too?  Or, is there a possibility that the partial occupancy was actually not set so that the previous pymatgen version didn't complain at that point.  I'm just trying to understand the problem completely.

In any event, the NearNeighbor class should be able to successfully deal with partial occupancies, and I'm working on getting that fixed.

**Comment by nisse3000** [comment] 2018-04-02 21:54
It also looks like being specifically a problem of the VoronoiNN because the MinimumDistanceNN works perfectly.

print(Pt, PtPd)
print('Pt Coordination: ', MinimumDistanceNN().get_cn(Pt, 0))
print('PtPd Alloy Coordination: ', MinimumDistanceNN().get_cn(PtPd, 0))

-->

('Pt Coordination: ', 12)
('PtPd Alloy Coordination: ', 12)

**Comment by GerardMattei** [comment] 2018-04-04 12:27
Hi Nils, 
Thanks for the response: in the previous version of pymatgen, I had used the VoronoiCoordFinder class in pymatgen.analysis.structure_analyzer, which (I assume) became the new VoronoiNN class in the latest release. I used the get_coordination_number() and get_coordinated_sites() methods to extract coordination number and atom-atom distances.

I'm pretty sure the problem is related to the new VoronoiNN class because I had tested the code using the PtPd mixed occupancy (as seen above), along with another material which had only partial sodium occupancies, in the old version of the code. When I updated to pymatgen 2018, I used the same structures/code as before, only updating to the new VoronoiNN class. 

Would it help if I were to send you the old code I had used, which I can verify worked without any issues?

**Comment by nisse3000** [comment] 2018-06-25 18:28
Hi @GerardMattei,
can you pull the latest pymatgen version and test whether your issue is resolved by the changes I made to VoronoiNN in PR #1182?

**Comment by GerardMattei** [comment] 2018-07-02 01:05
Hi Nils,

Tentatively it looks like that took care of the problem - I still want to test a few things, but I tried the original test code above using both mixed PtPd occupancies and partial Pt occupancies and the VoronoiNN returns the same coordination number as the original pristine Pt structure, which is exactly what I was hoping to see. 

Thank you again for your help on this,
-Gerry

**Comment by nisse3000** [comment] 2018-07-02 17:54
Hi @GerardMattei,

that sounds great. I'd then suggest that @shyuep closes the issue. You can still reopen it later, but the problem that you described seems to be dealt with.

**Closed** 2018-07-02 17:58 UTC
