### ISSUE TITLE
MPRester fails to retrieve entries

### ISSUE THREAD

**Issue by fxcoudert** [materialsproject/pymatgen#1331] opened 2018-11-14 16:32 UTC
**Describe the bug**
Results from a particular MPRester query are wrong (no entries are retrieved, even though they exist).

**To Reproduce**

Running this script:

```
from pymatgen import MPRester
api = MPRester('XXXXXXXXXXX')
n = 0
for i in range(1, 8):
    entries = api.get_entries({'nelements': i}, property_data=['elasticity'])
    n += len(entries)
    print(f'{len(entries)} entries with {i} elements')
print(f'Total: {n}')
```

(where `XXXXXXXXXXX` is a valid MAPI key) gives the following output:

```
$ python3 ./a.py
565 entries with 1 elements
13832 entries with 2 elements
0 entries with 3 elements
22875 entries with 4 elements
6636 entries with 5 elements
882 entries with 6 elements
68 entries with 7 elements
Total: 44858
```

**Expected behavior**
The number of structures with 3 elements and elastic data should be 8028, not zero. This can be checked on the database website by running the following query: `https://materialsproject.org/#search/materials/{"has_elasticity"%3Atrue%2C"mpquery"%3A"{'nelements'%3A%203}"}`

**System info**
Has been reproduced with various Python installations, on macOS and Linux, with pymatgen-2018.11.6.

**Comment by shyuep** [comment] 2018-11-14 16:42
The reason why this fails is because too much data is requested in one query. If you just need the elasticity data, it is not good to do it via this route. It asks for a lot of unnecessary data. Use the query method to do a more fine-grained query. REfer to the http://bit.ly/materialsapi and http://matgenb.materialsvirtuallab.org for examples.

That said, the code is bad for not highlighting the error properly and just giving a zero entries response. I am pushing a fix for this part.

**Closed** 2018-11-14 16:44 UTC

**Comment by shyuep** [comment] 2018-11-14 16:45
In particular, look at this notebook for a specific example on how elasticity data can be obtained. http://matgenb.materialsvirtuallab.org/2017/03/02/Getting-data-from-Materials-Project.html

**Comment by fxcoudert** [comment] 2018-11-14 17:20
Using `query` gives me `pymatgen.ext.matproj.MPRestError: REST query returned with error status code 504`:

```
rmeur ~ $ cat a.py 
from pymatgen import MPRester
api = MPRester('XXXXXXXXXXX')

res = api.query({"elasticity": {"$exists": True}},
                properties=['task_id', 'pretty_formula', 'elasticity'])
print(len(res))
rmeur ~ $ python3 ./a.py
Traceback (most recent call last):
  File "/Users/fx/anaconda3/lib/python3.7/site-packages/pymatgen/ext/matproj.py", line 152, in _make_request
    .format(response.status_code))
pymatgen.ext.matproj.MPRestError: REST query returned with error status code 504

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./a.py", line 5, in <module>
    properties=['task_id', 'pretty_formula', 'elasticity'])
  File "/Users/fx/anaconda3/lib/python3.7/site-packages/pymatgen/ext/matproj.py", line 737, in query
    mp_decode=mp_decode)
  File "/Users/fx/anaconda3/lib/python3.7/site-packages/pymatgen/ext/matproj.py", line 157, in _make_request
    raise MPRestError(msg)
pymatgen.ext.matproj.MPRestError: REST query returned with error status code 504. Content: b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>504 Gateway Time-out</title>\n</head><body>\n<h1>Gateway Time-out</h1>\n<p>The gateway did not receive a timely response\nfrom the upstream server or application.</p>\n<hr>\n<address>Apache/2.2.15 (CentOS) Server at www.materialsproject.org Port 443</address>\n</body></html>\n'
```

**Comment by shyuep** [comment] 2018-11-14 17:23
This is a Materials Project issue. Donny should investigate.

Shyue Ping

**Comment by dwinston** [comment] 2018-11-14 17:34
@fxcoudert too much data is being requested in one query - that is why you are getting the error. The example notebook to which @shyuep linked was written when there were only 4,430 elastic tensors, whereas now there are nearly 14,000. I am working on a pull request (#1324) to adapt `MPRester.query` to better handle large requests.

**Comment by fxcoudert** [comment] 2018-11-14 17:39
@dwinston I have tried to find the documentation on query size limits or rate limits in MAPI, but couldn't. Did I miss it?

**Comment by dwinston** [comment] 2018-11-14 17:44
@fxcoudert it is not a limit we impose, but a limitation of the way we serve the data dynamically. Our API server queries the database, fetches the data, and returns it to you. Because the API server has limited RAM, it simply cannot serve too-large data requests in a single query. If we e.g. buffered and streamed the results to a temporary file, then we could give you a link to the file and you could download a giant file, but we favor the simplicity of in-RAM dynamic queries. I am adding functionality to `MPRester.query` to chunk queries.

**Comment by thienbinh92** [comment] 2022-02-15 05:33
Hi, I got a similar error when trying this example [http://matgenb.materialsvirtuallab.org/2016/09/08/Data-driven-First-Principles-Methods-for-the-Study-and-Design-of-Alkali-Superionic-Conductors-Part-2-Phase-and-Electrochemical-Stability.html](url). Here is the code:
`rester = MPRester(api_key="**********Cu9**********")
mp_entries = rester.get_entries_in_chemsys(["Li", "P", "S", "Cl"])`
An the error is: 
`MPRestError: HTTPSConnectionPool(host='materialsproject.org', port=443): Max retries exceeded with url: /rest/v2/query (Caused by SSLError(SSLError("bad handshake: SysCallError(54, 'ECONNRESET')")))`
May I ask if the website is under maintenance or changed?

**Comment by nmehjabin** [comment] 2023-07-24 15:22
> @fxcoudert it is not a limit we impose, but a limitation of the way we serve the data dynamically. Our API server queries the database, fetches the data, and returns it to you. Because the API server has limited RAM, it simply cannot serve too-large data requests in a single query. If we e.g. buffered and streamed the results to a temporary file, then we could give you a link to the file and you could download a giant file, but we favor the simplicity of in-RAM dynamic queries. I am adding functionality to `MPRester.query` to chunk queries.

I am having similar issue. I understand the problem why it's happening, however, is there any way we can do it? 
----------------------------------------------------------------------------------------------------------------------------
MPRestError: REST query returned with error status code 504 on URL https://api.materialsproject.org/materials/core/?deprecated=False&elements=Zr%2CO&_limit=1000&_fields=material_id%2Cstructure with message:
Server timed out trying to obtain data. Try again with a smaller request.
