### ISSUE TITLE
New pymatgen version 

### ISSUE THREAD

**Issue by JaGeo** [materialsproject/pymatgen#3744] opened 2024-04-10 05:48 UTC
### Feature Requested

I would like to ask for a new pymatgen version after many new implementations in the last month. We currently face a bug in the atomate2 LOBSTER workflow that can only be fixed with a new version. (Cc @naik-aakash )

### Proposed Solution

Release of a new version. 

I am wondering if the many new type hints and improvements in recent weeks might have an effect on other packages (atomate2, matminer). Do you expect anything like this, @janosh ?

**Comment by janosh** [comment] 2024-04-10 06:08
there was this PR https://github.com/materialsproject/pymatgen/pull/3624 which you know the downstream implications of better than I.

there also [appears to have been an accidental change](https://github.com/materialsproject/pymatgen/pull/3705/files#r1558895539) in https://github.com/materialsproject/pymatgen/pull/3705

**Comment by JaGeo** [comment] 2024-04-10 06:12
> there was this PR #3624 which you know the downstream implications of better than I.
> 
> there also [appears to have been an accidental change](https://github.com/materialsproject/pymatgen/pull/3705/files#r1558895539) in #3705

Yes, this one will fix our bug and add some enhancements! Thank you. 😃

**Comment by DanielYang59** [comment] 2024-04-10 06:14
Ah I'm terribly sorry. I cannot remember why I made that change in https://github.com/materialsproject/pymatgen/pull/3705#discussion_r1558895539. And it certainly should not be there. I'm looking into the commit history now.

**Comment by Andrew-S-Rosen** [comment] 2024-04-11 22:28
Subscribing because I'm waiting on the next release too :)

**Comment by janosh** [comment] 2024-04-12 05:59
closed by [v2024.4.12](https://github.com/materialsproject/pymatgen/releases/tag/v2024.4.12).

this is a larger-than-usual release with many small and a couple large changes. please report any issues that might come up. e.g. i confirmed that https://github.com/materialsproject/pymatgen/pull/3624 breaks `atomate2` tests

**Comment by JaGeo** [comment] 2024-04-12 06:16
@naik-aakash and I are on it! Thanks!

Side note: We were thinking about a meta package in the foundation meeting but maybe checking automatically in pymatgen before release if it breaks atomate2 would be enough?

**Comment by JaGeo** [comment] 2024-04-12 06:29
@janosh : This method name got changend in a way that it does not even describe what it does anymore: https://github.com/materialsproject/pymatgen/blob/696aace7fb082a1f9d959201059fe1a9c9a81c22/pymatgen/electronic_structure/cohp.py#L160
Leading to failures in LobsterPy. 

Will investigate further but this needs to be changed in any case.

**Comment by JaGeo** [comment] 2024-04-12 15:57
Collecting some more issues here: https://github.com/materialsproject/pymatgen/pull/3705#issuecomment-2051980163

**Comment by janosh** [comment] 2024-04-16 04:55
i think this can be called closed by [v2024.4.13](https://github.com/materialsproject/pymatgen/releases/tag/v2024.4.13)?

**Closed by janosh** 2024-04-16 04:55 UTC
Labels: enhancement

**Comment by JaGeo** [comment] 2024-04-16 04:58
Yes, thank you! 😄
