### ISSUE TITLE
Typo in pymatgen.io.abinit.abitimer module AbinitTimerParserError

### ISSUE THREAD

**Issue by pjf295** [materialsproject/pymatgen#3208] opened 2023-08-03 09:34 UTC
#### Description

While I have been using pymatgen for a while, I recently wanted to try using abipy to do some calculations in abinit. Using one of the example jupyter notebooks, there is an import line

`pymatgen.io.abinit.abitimer import AbinitTimerParserError
`
The import fails. Investigation of the modules available shows that there is a module "AbinitTimerParseError".  My guess is that this was meant to be "AbinitTimerParserError" as the Jupyter notebook line indicates.

#### Repro

1. install abipy using pip
2. start ipython
3. "import abipy"

This fails within the abipy.abitimer module with the error message 

```
ImportError                               Traceback (most recent call last)
Cell In[5], line 1
----> 1 from pymatgen.io.abinit.abitimer import AbinitTimerParserError

ImportError: cannot import name 'AbinitTimerParserError' from 'pymatgen.io.abinit.abitimer' (/data/miniconda/envs/abipy/lib/python3.11/site-packages/pymatgen/io/abinit/abitimer.py)

```

The line, "from pymatgen.io.abinit.abitimer import AbinitTimerParseError" works fine however. The pymatgen documentation only shows the module AbinitTimerParserError suggesting that a typo exists in pymatgen.io.abinit.abitimer

I manually fixed the error by changing two lines in pymatgen.io.abinit.abitimer

Line 35
class AbinitTimerParseError(ParseError): -> class AbinitTimerParserError(ParseError):

Line 58
Error = AbinitTimerParseError -> Error = AbinitTimerParserError

#### Expected behavior

Successful import of abipy

#### Environment

Relevant versions and platform info:

Centos 7
pymatgen-2023.7.20
abipy-0.9.3
#### Additional context

More context like related issues/PRs.

**Comment by janosh** [comment] 2023-08-03 16:59
Duplicate of https://github.com/materialsproject/pymatgen/issues/3170. See https://github.com/materialsproject/pymatgen/issues/3170#issuecomment-1644272034 for the fix.

**Closed by janosh** 2023-08-03 16:59 UTC
Labels: outdated, io, duplicate
