### ISSUE TITLE
pymatgen no "_init_.py" file

### ISSUE THREAD

**Issue by YXT996** [materialsproject/pymatgen#4050] opened 2024-09-07 08:36 UTC
### Python version

Python3.9.19

### Pymatgen version

2024.8.9

### Operating system version

Linux: miniconda

### Current behavior

![Snipaste_2024-09-07_16-29-32](https://github.com/user-attachments/assets/b44cbf29-25e9-4906-93b5-450d9e5cc53b)
![Snipaste_2024-09-07_16-31-47](https://github.com/user-attachments/assets/51a214b6-d9d2-419c-8608-9833ddfb198a)
In conda env, pip install, no "_init_py" file

### Expected Behavior

"_init_py" file

**Comment by janosh** [comment] 2024-09-07 10:57
closing as duplicate of #4049.

**Closed by janosh** 2024-09-07 10:57 UTC
Labels: bug
