### ISSUE TITLE
Reading and writing POTCAR files is broken

### ISSUE THREAD

**Issue by henriquemiranda** [materialsproject/pymatgen#3068] opened 2023-06-14 12:40 UTC
#### Description

Reading and writing POTCAR file with the Potcar class from pymatgen.io.vasp seems broken.

#### Repro

To reproduce the problem, I start with a file:

POTCAR
```
 PAW Sb 04Feb1998
  5.00000000000000
 [...]
  0.000000000000E+00  0.000000000000E+00  0.000000000000E+00
 End of Dataset
  PAW Te 03Oct2001
   6.00000000000000
 [...]
  0.000000000000E+00  0.000000000000E+00  0.000000000000E+00 0.000000000000E+00  0.000000000000E+00
 End of Dataset
```

I use the following script to copy the POTCAR:
```
from pymatgen.io.vasp import Potcar
potcar = Potcar.from_file('POTCAR')
potcar.write_file('POTCAR_NEW')
```

the resulting file becomes:
POTCAR_NEW
```
 PAW Sb 04Feb1998
  5.00000000000000
 [...]
  0.000000000000E+00  0.000000000000E+00  0.000000000000E+00End of Dataset
  PAW Te 03Oct2001
   6.00000000000000
 [...]
  0.000000000000E+00  0.000000000000E+00  0.000000000000E+00 0.000000000000E+00  0.000000000000E+00End of Dataset
```

#### Expected behavior

I would expect the files in POTCAR_NEW to be the same as the ones in POTCAR

#### Problem

The problem originated after #2910 was merged.
Perhaps @jmmshn and @janosh have some insight.
From the discussion, it looks like the relevant tests were broken by these changes and then deactivated.

I also mention @MichaelWolloch since he knows about the handling of the hashes of the POTCAR files.

**Comment by janosh** [comment] 2023-06-14 13:37
Just to confirm, the problem is `"End of Dataset"` not being on a new line?

**Comment by henriquemiranda** [comment] 2023-06-14 13:43
Yes, exactly

**Comment by jmmshn** [comment] 2023-06-14 14:08
Thanks for reporting this!
I think the last fix on parsing fixed one white space problem and created another. I'm currently on family leave until the end of next week I can fix it when I come back.

**Comment by MichaelWolloch** [comment] 2023-06-14 14:33
I think the problem is in reading the POTCAR from file. The `.stip()` method is used when constructing the PotcarSingle objects when it should not be used.

This should work (in the Potcar class):
~~~
    @staticmethod
    def from_file(filename: str):
        """
        Reads Potcar from file.

        :param filename: Filename
        :return: Potcar
        """
        with zopen(filename, "rt") as f:
            fdata = f.read()
        potcar = Potcar()

        functionals = []
        for p in fdata.split("End of Dataset\n"):
            if p.strip():
                single = PotcarSingle(p + "End of Dataset\n")
                potcar.append(single)
                functionals.append(single.functional)
        if len(set(functionals)) != 1:
            raise ValueError("File contains incompatible functionals!")
        potcar.functional = functionals[0]
        return potcar
~~~
It is essentially what was there before commit 1e9119a07e0.

Regarding the discussion in #2910, I understand that the hash system is a bit brittle and cumbersome. But I do not think commenting out tests is the way to go. If one needs to keep the hash checks, then one should try and add more unit tests precisely because it is a fickle thing. Otherwise, one should just get rid of it entirely.

I want to stress that the issue @henriquemiranda describes does not only give a hash warning. The resulting POTCAR is not valid and will crash VASP. So this has not strictly to do with the hash system.

**Comment by jmmshn** [comment] 2023-06-16 08:19
I think this can also work:
```
- single = PotcarSingle(p_strip + "End of Dataset\n")
+ single = PotcarSingle(p_strip + "\nEnd of Dataset\n")
```
I believe `p_strip` was used here to help make sure that the output POTCARs were more consistent with the hope that we implement some kind of more usable hashing in the future but that obviously backfired.

I'm not actually able to pull the code since I'm in China (on family leave) until the end of next week and the VPN has been really slow.
So if this is an emergency someone else will have to patch and test this.  Apologies.

**Comment by MichaelWolloch** [comment] 2023-06-16 08:52
This version does produce a valid POTCAR, but it still fails the implemented hash checks. I really do not see the point in reformatting POTCARs. No full file hash can work consistently for both POTCARs that are just taken from the library and maybe concatenated together, and ones that have been reformatted by pymatgen.

I took me a lot of effort to repair the hashing system that was throwing warnings every time a POTCAR was used for a long time in #2762. I tried to make the hashing system more usable and future proof by using POTCAR internal hashes as well and not only the ones in the pymatgen hash tables. I am the first to admit that the solutions were not very easy to read because of all the regex statements, but at least it worked...

**Comment by MichaelWolloch** [comment] 2023-06-16 15:29
No apologies needed @janosh , I realize of course that nobody is doing anything out of malice.
My only concern is that tests are being deleted and warnings ignored. Of course the header of each PotcarSingle should be accessible from the Potcar object.

And I would also not be mad if the hashing checks are completely removed at some point. I personally think that they have value, and that POTCARs should never be modified (as is also the VASP companies policy), but one does not necessarily have to check for modification by hashes.

The code I posted above and also gives the right headers by the way (using @henriquemiranda's example):
~~~
from pymatgen.io.vasp import Potcar

potcar = Potcar.from_file("POTCAR_old")
potcar.write_file("POTCAR")
print({d.header for d in potcar})
~~~
gives (without a warning due to a failed hash):
`{'PAW Sb 04Feb1998', 'PAW Te 03Oct2001'}`

**Comment by MichaelWolloch** [comment] 2023-06-16 16:07
Fine with me. Just be careful that the POTCARs are not modified in a way that breaks functionality as happened in #2910 in the future.

**Comment by jmmshn** [comment] 2023-06-16 23:54
I see. Thanks for the context. As I said in the other thread I'm not familiar with the hashing part of the at all.
If I had known it was being recently worked on I would not have agreed to removing the tests.
I guess we just need a very small PR to fix the newline thing first and look at adding the tests back in later?
@janosh can you do this, I literally cannot `git clone` right now.

**Comment by jmmshn** [comment] 2023-06-16 23:58
agreeded there should have a basic POTCAR parsing test I'll make sure to add it when I get back.

**Comment by MichaelWolloch** [comment] 2023-06-19 08:21
Thanks @jmmshn , I am happy to take part in discussions on how this could look without using hashes or executing VASP to see if the POTCAR is valid.

**Comment by matthewkuner** [comment] 2023-06-30 20:30
@jmmshn just pinging you about the POTCAR parsing/validation test

**Comment by MichaelWolloch** [comment] 2023-07-02 19:17
I am on holiday until the 10th. I am happy to comment on any validation test that is proposed. However, I still think that the hashing is a pretty optimal way of doing the validation.  If someone proposes something better I am happy to help with implementation and testing however, and I would also of course be willing to work on the hashing if we decide to keep it after all.

**Comment by MichaelWolloch** [comment] 2023-08-02 15:43
@jmmshn , as you can see, I just made the PR that should fix issue we discovered in atomate. I think this can be closed, and if further discussion is needed, it can go there.

**Closed** 2023-08-15 16:26 UTC
Labels: io, needs discussion, vasp
