### ISSUE TITLE
POTCAR file hashes appear to be incorrect

### ISSUE THREAD

**Issue by bjmorgan** [materialsproject/pymatgen#1746] opened 2020-01-28 11:10 UTC
The `vasp_potcar_file_hashes.json` ([here](https://github.com/materialsproject/pymatgen/blob/master/pymatgen/io/vasp/vasp_potcar_file_hashes.json)) is supposed to contain md5 hashes of POTCAR files (if I have this understood correctly). But the hashes in the file do not match the hashes generated from `md5sum POTCAR` from the command line.

e.g. using the PBE_54 Ac POTCAR
```python
from pymatgen.io.vasp.inputs import PotcarSingle

psingle = PotcarSingle.from_file(filename='POTCAR_PBE54_Ac')

print(psingle.hash)
# note: this hash is included in the vasp_potcar_pymatgen_hashes.json file

from hashlib import md5
print(md5(psingle.data.encode("utf-8")).hexdigest())
# This is the same hash generated using `md5sum POTCAR` from the command line.
# it is *not* included in the vasp_potcar_file_hashes.json file
```
produces
```
4175a0a39300f5c90c84142814f8cc72
cb0e0b98d520a284cf11d1161f25e6a5
```
The first hash is included in the `vasp_potcar_pymatgen_hashes.json` file:
```
grep -c 4175a0a39300f5c90c84142814f8cc72 vasp_potcar_pymatgen_hashes.json 
1
```
The second hash is *not* included in the `vasp_potcar_file_hashes.json` file:
```
grep -c cb0e0b98d520a284cf11d1161f25e6a5 vasp_potcar_file_hashes.json 
0
```

Note: this is using the "original unvie release version" PBE_54 pseudopotential files.

Using the updated PBE_54 pseudopotentials gives:
```
md5 POTCAR 
MD5 (POTCAR) = 2837362d49736e188edb5cc8d2a39c71
grep -c 2837362d49736e188edb5cc8d2a39c71 vasp_potcar_file_hashes.json 
0
```

**Comment by shyuep** [comment] 2020-01-28 15:34
Thanks for reporting this.
@mkhorton @shyamd I honestly dislike the file hash approach to dealing with POTCARs. Should we just do away with this? I think basic checks such as the functional, date and parameters would suffice?

**Comment by shyamd** [comment] 2020-01-28 16:07
These aren't supposed to be file hashes, but rather data hashes, so this is the expected behavior.

**Comment by bjmorgan** [comment] 2020-01-28 16:23
From my testing, the data hashes work as intended. But these are only currently included for Materials Project compatible pseudopotential sets. Other PP choices fall back to file hashes.

**Comment by shyamd** [comment] 2020-01-28 16:36
This check was to ensure that when non-MP researchers ran calculations they could be sure those pseudopotentials were the same as what we ran our calculations with. This should just be a warning that maybe can be toggled off via `PMG_` environment variable?

**Comment by mkhorton** [comment] 2020-01-28 17:49
@rkingsbury can you check the docstring here https://github.com/materialsproject/pymatgen/blob/3189eb225831f90db61c296ac1175e1811031a97/pymatgen/io/vasp/sets.py#L2856 ?

Is it correct that the data hashes (`pymatgen_hashes`) are only available for the old PP set, I thought these were added for all PPs?

@shyuep There are only a handful of pseudopotentials distributed with VASP, in principle hashing shouldn't be causing grief unless users manually edit or generate their own POTCARs, however we may have a bug here.

**Comment by rkingsbury** [comment] 2020-01-28 17:52
@mkhorton I'm investigating now. I believe we do have a bug in the file hashes. Will update shortly.

**Comment by rkingsbury** [comment] 2020-01-28 18:04
As best I can tell, the original hash files were generated on an incomplete set of POTCARs. For example, the "PBE" set was not included in the original files. I've recomputed the hash files to include every PSP currently installed on Cori (Vasp 5.4.4). 

As @bjmorgan pointed out, the data hashes were correct (just incomplete), while it appears some of the file hashes were incorrect, possibly due to the changes to the metadata noted by Paul_Fons in the related [discussion thread](https://discuss.matsci.org/t/hash-failure-for-potcar/3461).

**Comment by mkhorton** [comment] 2020-01-28 18:06
Thanks for submitting the fix so promptly @rkingsbury

**Comment by rkingsbury** [comment] 2020-01-28 18:11
Thanks for reporting @bjmorgan! Please let us know if you have any further problems after the fix is merged.

**Comment by bjmorgan** [comment] 2020-01-28 18:17
If it helps for checking, I have what I believe to be a full set of file hashes at https://github.com/bjmorgan/vasppy/tree/master/vasppy/data (`*_md5.yaml`)

**Comment by mkhorton** [comment] 2020-01-28 18:20
@bjmorgan thanks, that might help. We're leaning on the "data" hashes more that literal md5 checksums because VASP did make a revision release of one of their POTCAR sets where they changed metadata (typos/incorrect strings in TITEL) but the POTCARs themselves were functionally equivalent. I believe this only happened once, but we do need to catch it.

**Comment by bjmorgan** [comment] 2020-01-28 18:24
@mkhorton I actually updated my dataset today when I learned about this from the discussion thread. The new-metadata "recommended" PPs are listed in the `PBE_54r_md5.yaml` and `LDA_54r_md5.yaml` files. Testing against only the PP data seems more robust, and avoids this issue.

**Comment by bjmorgan** [comment] 2020-01-28 23:11
The updated hashes in https://github.com/materialsproject/pymatgen/pull/1749 do not appear to include the examples given in the original post (and are possibly all the same hashes as in `master`; with the exception of the PP sets added during this commit).

**Comment by rkingsbury** [comment] 2020-01-28 23:18
@bjmorgan do you mean the file hashes? Yes, I was checking our recomputed hashes against yours and noticed the same thing. Did you compute your hashes from the `.data` attribute of the `PotcarSingle` object (as in your example) or directly from the file itself?

**Comment by rkingsbury** [comment] 2020-01-28 23:28
@bjmorgan it appears that you get a different hash depending upon whether you hash a Potcar or a PotcarSingle object. For example:

```
from hashlib import md5

path = Path("POTCAR.Ac.gz")

psingle = PotcarSingle.from_file(path)
potcar = Potcar.from_file(path)

hash1 = md5(psingle.data.encode('utf-8')).hexdigest()
hash2 = md5(potcar[0].data.encode('utf-8')).hexdigest()

print(hash1)
print(hash2)
```
gives
```
cb0e0b98d520a284cf11d1161f25e6a5
61fb9dcc007c8d625d77210ebc269828
```

We used the second approach to compute the hashes, which is why they are not equal to those you computed. We're revisiting whether this is the best approach though as it clearly leads to confusion!

**Comment by bjmorgan** [comment] 2020-01-28 23:34
The difference is because the final `\n` has been stripped in the case of `potcar[0].data`.

**Comment by bjmorgan** [comment] 2020-01-28 23:38
In which case you have a bug in `validate_potcar_hash()` https://github.com/materialsproject/pymatgen/blob/master/pymatgen/io/vasp/sets.py#L2879
where you use the `PotcarSingle` hash during validation.

**Comment by rkingsbury** [comment] 2020-01-28 23:41
Thank you @bjmorgan , we're making progress. Yes, thanks to our discussion I just recognized that bug and have pushed a recomputed set of hashes using PotcarSingle. This bug was causing some extra warnings during our tests that we assumed were due to some of the POTCARs distributed with pymatgen having old / out of date metadata.

Out of about 3,000 file hashes, I now show only about 650 that differ from yours. I'll reply shortly when I figure out which files those differences are coming from

**Comment by rkingsbury** [comment] 2020-01-29 00:20
There are 622 files in the PBE_54r and LDA_54r sets combined, so those account for most of the missing hashes. We apparently don't have those PPs installed on our system.

Hashes differ for the following PBE PPs:

```
PBE B_h
PBE C_h
PBE Ce
PBE Eu
PBE F_h
PBE Gd
PBE Ge_d
PBE H_h
PBE Li_sv
PBE Lu
PBE Mg_pv
PBE N_h
PBE Na_pv
PBE Nd
PBE O_h
PBE Pd
PBE Pm
PBE Pr
PBE Si_h
PBE Sm
PBE Sm_3
PBE Tm
PBE Yb
```

And finally, there are discrepancies for Mg_pv and Si_h that I think are related to the fact that both of these PPs have multiple versions (on our system at least) with filenames like `POTCAR.Mg_pv.gz', 'POTCAR.Mg_pv.old.gz', 'POTCAR.Mg_pv_GW.gz'

**Comment by bjmorgan** [comment] 2020-01-29 00:48
For `PBE B_h` I get
```python
from pymatgen.io.vasp.inputs import PotcarSingle
psingle = PotcarSingle.from_file(filename='POTCAR_PBE54_B_h')

from hashlib import md5
print(md5(psingle.data.encode("utf-8")).hexdigest())
```
```
501131776b38fb29fe50c430b72d2643
```
and
```$ md5 POTCAR_PBE54_B_h 
MD5 (POTCAR_PBE54_B_h) = 501131776b38fb29fe50c430b72d2643
```

**Comment by rkingsbury** [comment] 2020-01-29 01:14
@bjmorgan thanks for all the assistance in troubleshooting this. We've merged a provisional fix that uses the more complete set of `Psingle` hashes and changes the `BadHashError` into a warning so that it won't be fatal. 

Please test and let us know how things are working. We need to continue investigating whether the PP's that we have available on Cori have the most up to date metadata (based on your contributions it sounds like they are not). If that's the case, we'll try to update them and get a more complete set of hashes pushed soon.

**Closed** 2020-01-30 00:25 UTC
